calgaryhacks/ParticleHooks/urls.py
from django.conf.urls import url
from ParticleHooks.views import ProcessHookView, profile, logoutuser

from ParticleHooks.views import addDevice, removeDevice, addNumber, removeNumber

app_name = 'ParticleHooks'

urlpatterns = [
	url(r'^hooks$', ProcessHookView.as_view(), name='hooks'),
    url(r'^profile$', profile, name='profile'),
    url(r'^logoutuser$', logoutuser, name='logoutuser'),
    
    url(r'^addDevice$', addDevice, name="addDevice"),
    url(r'^removeDevice$', removeDevice, name='removeDevice'),

    url(r'^addNumber$', addNumber, name='addNumber'),
    url(r'^removeNumber$', removeNumber, name='removeNumber')
    # url(r'^signup$', signup, name='signup')
]

calgaryhacks/calgaryhacks/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^ParticleHooks/', include('ParticleHooks.urls')),
    url(r'^', include('main.urls')),
]

calgaryhacks/main/urls.py
from django.conf.urls import url
from . import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.MainPage.as_view(), name='index'),
]

calgaryhacks/ParticleHooks/models.py
from django.db import models
from django.conf import settings
# Create your models here.
from django.contrib.auth.models import User 


class Devices(models.Model):
	coreid = models.CharField(max_length=24, unique=True)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)



class PhoneNumber(models.Model):
	phone_num = models.CharField(max_length=11)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


# class Client(User):
# 	phone_num = models.CharField(max_length=11)


# 	class Meta:
# 		proxy = True

calgaryhacks/main/models.py
from django.db import models

# Create your models here.

calgaryhacks/main/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'password']

calgaryhacks/ParticleHooks/views.py
import os

from django.shortcuts import render, redirect
from django.http import HttpResponse

from django.views.generic import View 

import json
from braces.views import CsrfExemptMixin
from twilio.rest import Client 
from django.contrib.auth.models import User
from django.contrib.auth import logout
from django.contrib.auth.decorators import user_passes_test

from .models import Devices, PhoneNumber

def is_user_active(user):
    return user.is_active

@user_passes_test(is_user_active, login_url='/')
def profile(request):
	return render(request, 'ParticleHooks/profile.html', {})

@user_passes_test(is_user_active, login_url='/')
def addDevice(request):
	post = request.POST
	device = Devices(user=request.user)
	device.coreid = post['coreid']
	device.save()
	print('add d:', request.POST)
	return redirect('ParticleHooks:profile')

@user_passes_test(is_user_active, login_url='/')
def removeDevice(request):
	post = request.POST
	Devices.objects.filter(id=int(post['deviceid'])).delete()
	print('remove d:', request.POST)
	return redirect('ParticleHooks:profile')

@user_passes_test(is_user_active, login_url='/')
def addNumber(request):
	post = request.POST
	num = PhoneNumber(user=request.user)
	num.phone_num = post['numberid']
	num.save()
	print('add n:', request.POST)
	return redirect('ParticleHooks:profile')

@user_passes_test(is_user_active, login_url='/')
def removeNumber(request):
	post = request.POST
	PhoneNumber.objects.filter(id=int(post['numberid'])).delete()
	print('remove n:', post['numberid'])
	return redirect('ParticleHooks:profile')

@user_passes_test(is_user_active, login_url='/')
def logoutuser(request):
	logout(request) 
	return redirect('main:index')

class ProcessHookView(CsrfExemptMixin, View):

	def sendSMSMessage(self, msg, to):
		account_sid = 'AC19460052ec76211b5ea9a719ee78bbed'
		auth_token = '27dd45ac6bf1123da30daccce8746475'
		from_num = '+15873551468'

		client = Client(account_sid, auth_token)

		message = client.messages.create(
			to,
			from_=from_num,
			body=msg
			)

		return message 

	def processJSON(self, json_msg, to):
		if 'sms' in json_msg:
			self.sendSMSMessage(json_msg['sms'], to)

	def post(self, request, *args, **kwargs):
		# print("RAW: ", request.body)
		info = json.loads(request.body)
		# print("JSON: ", info)
		data = info['data']
		
		if type(data) is str:
			data = json.loads(data)

		# print("data: '"+ data+"'")
		print("data: ", data)
		# print("keys:", data.keys())
		msg = self.processJSON(data, '+14038605837')
		print("Message: ", msg)
		# data = json.loads(info['data'])
		# print("data: ", data)


		return HttpResponse()

calgaryhacks/main/views.py
from django.http import HttpResponse

from django.contrib.auth.models import User

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views import View 
from .forms import UserForm
from braces.views import CsrfExemptMixin

# Create your views here.


class MainPage(CsrfExemptMixin, View):
	form_class = UserForm
	template_name = 'main/index.html'

	def get(self, request):
		return render(request, self.template_name)

	def post(self, request):
		form = request.POST
		my_form = form.dict()
		if 'usernamesignup' in my_form:
			username = form['usernamesignup']
			password = form['passwordsignup']
			if not User.objects.filter(username=username).exists():
				user = User.objects.create_user(username, password)
				user.set_password(password)
				user.save()
		elif 'username' in my_form:
			username = form['username']
			password = form['password']

		user = authenticate(username=username, password=password)
		print(user)
		# print('Authenticating: ', user)
		if user is not None:
			if user.is_active:
				login(request, user)
				return redirect('ParticleHooks:profile')

		return render(request, self.template_name)
# def index(request):

# 	return render(request, 'main/index.html',{})

calgaryhacks/ParticleHooks/templates/ParticleHooks/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% load staticfiles %}
    <title>{% block title %}Calgary Hacks 2018{% endblock %}</title>
    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/simple-line-icons/css/simple-line-icons.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
    


    <!-- Plugin CSS -->
    <!-- <link rel="stylesheet" href="{% static 'device-mockups/device-mockups.min.css' %}"> -->

    <!-- Custom styles for this template -->
    <link href="{% static 'css/new-age.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'main:index' %}">Calgary Hacks 2018</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{% url 'ParticleHooks:logoutuser' %}">Logout</a>
            </li>
           
          </ul>
        </div>
      </div>
    </nav>

    

{% block body %}
{% endblock %}

    <footer>
      <div class="container">
        <p>&copy; Your Website 2018. All Rights Reserved.</p>
        <ul class="list-inline">
          <li class="list-inline-item">
            <a href="#">Privacy</a>
          </li>
          <li class="list-inline-item">
            <a href="#">Terms</a>
          </li>
          <li class="list-inline-item">
            <a href="#">FAQ</a>
          </li>
        </ul>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/new-age.min.js' %}"></script>
    <script src="{% static 'js/profile.js' %}"></script>
  </body>

</html>

calgaryhacks/ParticleHooks/templates/ParticleHooks/index.html
{% extends 'ParticleHooks/base.html' %}

{% block title %} {% endblock %}
{% block body %}
<div class="col-lg-6 col-sm-6">
	<div class="card hovercard">
	    <div class="card-background">
	        <img class="card-bkimg" alt="" src="http://lorempixel.com/100/100/people/9/">
	        <!-- http://lorempixel.com/850/280/people/9/ -->
	    </div>
	    <div class="useravatar">
	        <img alt="" src="'img/demo-screen-1.jpg'">
	    </div>
	    <div class="card-info"> <span class="card-title">Pamela Anderson</span>

	    </div>
	</div>
	<div class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
	    <div class="btn-group" role="group">
	        <button type="button" id="stars" class="btn btn-primary" href="#tab1" data-toggle="tab"><span class="glyphicon glyphicon-star" aria-hidden="true"></span>
	            <div class="hidden-xs">Stars</div>
	        </button>
	    </div>
	    <div class="btn-group" role="group">
	        <button type="button" id="favorites" class="btn btn-default" href="#tab2" data-toggle="tab"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
	            <div class="hidden-xs">Favorites</div>
	        </button>
	    </div>
	    <div class="btn-group" role="group">
	        <button type="button" id="following" class="btn btn-default" href="#tab3" data-toggle="tab"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>
	            <div class="hidden-xs">Following</div>
	        </button>
	    </div>
	</div>

	    <div class="well">
	  <div class="tab-content">
	    <div class="tab-pane fade in active" id="tab1">
	      <h3>This is tab 1</h3>
	    </div>
	    <div class="tab-pane fade in" id="tab2">
	      <h3>This is tab 2</h3>
	    </div>
	    <div class="tab-pane fade in" id="tab3">
	      <h3>This is tab 3</h3>
	    </div>
	  </div>
	</div>

</div>
{% endblock %}

calgaryhacks/ParticleHooks/templates/ParticleHooks/loginSignup.html
{% extends 'main/base.html' %}

{% load staticfiles %}
{% block title %}Login and Registration Form{% endblock %}
{% block body %}
<link rel="stylesheet" href="{% static 'css/loginAndSignup.css' %}">
<section>
<div id="fullscreen_bg" class="fullscreen_bg"/>
<div id="regContainer" class="container">
      <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-login">
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-6">
                <a href="#" class="active" id="login-form-link">Login</a>
              </div>
              <div class="col-xs-6">
                <a href="#" id="register-form-link">Register</a>
              </div>
            </div>
            <hr>
          </div>
          <div class="panel-body">
            <div class="row">
              <div class="col-lg-12">
                <form id="login-form" action="#" method="post" role="form" style="display: block;">
                  <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
                  </div>
                  <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
                  </div>
                  <div class="form-group text-center">
                    <input type="checkbox" tabindex="3" class="" name="remember" id="remember">
                    <label for="remember"> Remember Me</label>
                  </div>
                  <div class="form-group">
                    <div class="row">
                      <div class="col-sm-6 col-sm-offset-3">
                        <input type="submit" name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" value="Log In">
                      </div>
                    </div>
                  </div>
                </form>
                <form id="register-form" action="#" method="post" role="form" style="display: none;">
                  <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Username" value="">
                  </div>
                  <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password">
                  </div>
                  <div class="form-group">
                    <label for="confirm-password">Confirm password</label>
                    <input type="password" name="confirm-password" id="confirm-password" tabindex="2" class="form-control" placeholder="Confirm Password">
                  </div>
                  <div class="form-group">
                    <div class="row">
                      <div class="col-sm-6 col-sm-offset-3">
                        <input type="submit" name="register-submit" id="register-submit" tabindex="4" class="form-control btn btn-register" value="Register Now">
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>
{% endblock %}
<script src="{% static 'js/loginAndSignup.js' %}"></script>

calgaryhacks/ParticleHooks/templates/ParticleHooks/profile.html
{% extends 'ParticleHooks/base.html' %}

{% load staticfiles %}
{% block body %}
<table>
  <thead>
    <tr>
      <th colspan="3">Devices</th>
    </tr>
    <tr>
      <th colspan="2">Coreid</th>
    </tr>
  </thead>
  <tbody>
  	{% for device in user.devices_set.all %}
	<form class="form-horizontal" action="{% url 'ParticleHooks:removeDevice' %}" method="post">
  		{% csrf_token %}
  		<!-- <input type="" name="numberid" value="" display="false"> -->
	    <tr>
	      <td>{{ device.coreid }}</td>
	      <input type="hidden" name="deviceid" value="{{ device.id }}">
	      <td>
	      	<input type="submit" value=" Delete "/>
	      </td>
	    </tr>
    </form>
    {% endfor %}

    <form class="form-horizontal" action="{% url 'ParticleHooks:addDevice' %}" method="post">
    	{% csrf_token %}
    	<tr>
    		<td>
    			<input id="coreid" name="coreid" required="required" type="text" placeholder="Coreid"/>
    		</td>
    		<td><input type="submit" value="   Add   "/> </td>
    	</tr>
    </form>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th colspan="3">Phone Numbers</th>
    </tr>
    <tr>
      <th colspan="2">Number</th>
    </tr>
  </thead>

  <tbody>
  	{% for number in user.phonenumber_set.all %}
  	<form class="form-horizontal" action="{% url 'ParticleHooks:removeNumber' %}" method="post">
  		{% csrf_token %}
	    <tr>
	      <td>{{ number.phone_num }}</td>
	      <input type="hidden" name="numberid" value="{{ number.id }}">
	      <td>
	      	<input type="submit" value=" Delete "/>
	      </td>
	    </tr>
    </form>
    {% endfor %}

    <form class="form-horizontal" action="{% url 'ParticleHooks:addNumber' %}" method="post">
    	{% csrf_token %}
    	<tr>
    		<td>
    			<input id="numberid" name="numberid" required="required" type="text" placeholder="Phone number"/>
    		</td>
    		<td><input type="submit" value="   Add   "/> </td>
    	</tr>
        
        
    </form>
  </tbody>
</table>
{% endblock %}

calgaryhacks/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% load staticfiles %}
    <title>{% block title %}Calgary Hacks 2018{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/simple-line-icons/css/simple-line-icons.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="{% static 'device-mockups/device-mockups.min.css' %}">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/new-age.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/loginAndSignup.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Remote Protector</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#download">Download</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#features">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#SignUpLogin">Login/Sign up</a>
            </li>
           
          </ul>
        </div>
      </div>
    </nav>

{% block body %}
{% endblock %}

    <footer>
      <div class="container">
        <p>&copy; Your Website 2018. All Rights Reserved.</p>
        <ul class="list-inline">
          <li class="list-inline-item">
            <a href="#">Privacy</a>
          </li>
          <li class="list-inline-item">
            <a href="#">Terms</a>
          </li>
          <li class="list-inline-item">
            <a href="#">FAQ</a>
          </li>
        </ul>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/new-age.min.js' %}"></script>

  </body>

</html>

calgaryhacks/main/templates/main/base_old.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% load staticfiles %}

    <title>{% block title %}Calgary Hacks{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Start Bootstrap</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#services">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <header class="masthead text-center text-white d-flex">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>Your Favorite Source of Free Bootstrap Themes</strong>
            </h1>
            <hr>
          </div>
          <div class="col-lg-8 mx-auto">
            <p class="text-faded mb-5">Start Bootstrap can help you build better websites using the Bootstrap CSS framework! Just download your template and start going, no strings attached!</p>
            <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Find Out More</a>
          </div>
        </div>
      </div>
    </header>

{% block body %}
{% endblock %}

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/creative.min.js' %}"></script>

  </body>

</html>